/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: fft.i

package fft

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
extern void _wrap_Swig_free_fft_ddbce76051d01c2d(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_fft_ddbce76051d01c2d(swig_intgo arg1);
extern void _wrap_Print_fft_ddbce76051d01c2d(swig_type_1 arg1);
extern swig_intgo _wrap_Xrange_fft_ddbce76051d01c2d(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_Print_complex_fft_ddbce76051d01c2d(double arg1, double arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_fft_ddbce76051d01c2d(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_fft_ddbce76051d01c2d(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Print(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_Print_fft_ddbce76051d01c2d(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Xrange(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_Xrange_fft_ddbce76051d01c2d(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Print_complex(arg1 float64, arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Print_complex_fft_ddbce76051d01c2d(C.double(_swig_i_0), C.double(_swig_i_1))
}


